name: Node CI

on: [push]

jobs:
  build:
    container:
      image: mongo:latest
      ports:
        - 27017

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: docker://node:12-alpine
      with:
        node-version: ${{ matrix.node-version }}
    - name: yarn install and test
      run: |
        yarn install
        yarn test
      env:
        CI: true
