name: Node CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install mongodb
        run: |
          wget -qO - https://www.mongodb.org/static/pgp/server-4.2.asc | sudo apt-key add -
          echo "deb [ arch=amd64 ] https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.2 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-4.2.list
          sudo apt-get update && sudo apt-get install -y mongodb-org
        env:
          CI: true
      - name: Yarn install
        run: |
          yarn install
        env:
          CI: true
      - name: Test
        run: |
          yarn test
        env:
          CI: true
      - name: Coverage Test
        run: |
          yarn test:coveralls
        env:
          CI: true
